/*
 * Hola!
 */
package ventanas;

import java.util.ArrayList;

/**
 *
 * @author Sebastián Méndez <ITCH>
 */
public class IngreTab extends javax.swing.JDialog {

    /**
     * Creates new form IngreTab
     */
    int filas = 1, colums = 1, contPa = 1,contRe=1;
    String lista = "",reng="";
    ArrayList<String> enca = new ArrayList<>();
    ArrayList<String> rengs = new ArrayList<>();

    public IngreTab(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jtfFi.setText("" + filas);
        jtfCol.setText("" + colums);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenF = new javax.swing.JButton();
        btnMenC = new javax.swing.JButton();
        jtfFi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfCol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMasF = new javax.swing.JButton();
        btnMasC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfIngEnc = new javax.swing.JTextField();
        btnIng = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaLista = new javax.swing.JTextArea();
        btnLim = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfIngRe = new javax.swing.JTextField();
        btnIng1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaRenglones = new javax.swing.JTextArea();
        btnLim1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 440, 420));

        btnMenF.setText("-");
        btnMenF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenFActionPerformed(evt);
            }
        });

        btnMenC.setText("-");
        btnMenC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenCActionPerformed(evt);
            }
        });

        jLabel1.setText("Filas: ");

        jLabel2.setText("Columnas: ");

        btnMasF.setText("+");
        btnMasF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasFActionPerformed(evt);
            }
        });

        btnMasC.setText("+");
        btnMasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasCActionPerformed(evt);
            }
        });

        jLabel3.setText("Encabezados");

        btnIng.setText("Ingresar");
        btnIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngActionPerformed(evt);
            }
        });

        jtaLista.setColumns(20);
        jtaLista.setRows(5);
        jScrollPane1.setViewportView(jtaLista);

        btnLim.setText("Limpiar lista");
        btnLim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimActionPerformed(evt);
            }
        });

        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Renglones");

        btnIng1.setText("Ingresar");
        btnIng1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIng1ActionPerformed(evt);
            }
        });

        jtaRenglones.setColumns(20);
        jtaRenglones.setRows(5);
        jScrollPane2.setViewportView(jtaRenglones);

        btnLim1.setText("Limpiar lista");
        btnLim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLim1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(jtfFi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMasF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenF))
                            .addComponent(jtfIngEnc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIng)
                                .addGap(18, 18, 18)
                                .addComponent(btnLim))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCol, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMasC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenC))))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jtfIngRe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIng1)))
                        .addGap(18, 18, 18)
                        .addComponent(btnLim1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnMasF)
                    .addComponent(btnMenF)
                    .addComponent(jtfCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnMasC)
                    .addComponent(btnMenC))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIng)
                        .addComponent(btnLim))
                    .addComponent(jtfIngEnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIngRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIng1)
                    .addComponent(btnLim1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTerminar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenFActionPerformed
        // TODO add your handling code here:
        if (filas > 1) {
            filas--;
            jtfFi.setText("" + filas);
        }
    }//GEN-LAST:event_btnMenFActionPerformed

    private void btnMenCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenCActionPerformed
        // TODO add your handling code here:
        if (colums > 1) {
            colums--;
            jtfCol.setText("" + colums);
        }
    }//GEN-LAST:event_btnMenCActionPerformed

    private void btnMasFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasFActionPerformed
        // TODO add your handling code here:
        filas++;
        jtfFi.setText("" + filas);
    }//GEN-LAST:event_btnMasFActionPerformed

    private void btnMasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasCActionPerformed
        // TODO add your handling code here:
        colums++;
        jtfCol.setText("" + colums);
    }//GEN-LAST:event_btnMasCActionPerformed

    private void btnIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngActionPerformed
        // TODO add your handling code here:

        if (contPa <= colums) {
            String enc = jtfIngEnc.getText();
            enca.add(enc);
            lista += enc + "\n";
            jtaLista.setText(lista);
            contPa++;
        }
        jtfIngEnc.setText("");
    }//GEN-LAST:event_btnIngActionPerformed

    private void btnIng1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIng1ActionPerformed
        // TODO add your handling code here:
        if(contRe <= filas){
            String ren = jtfIngRe.getText();
            rengs.add(ren);
            reng+= ren+"\n";
            jtaRenglones.setText(reng);
            contRe++;
        }
        jtfIngRe.setText("");
    }//GEN-LAST:event_btnIng1ActionPerformed

    private void btnLimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimActionPerformed
        // TODO add your handling code here:
        contPa=1;
        enca= new ArrayList<>();
        lista = "";
        jtaLista.setText("");
    }//GEN-LAST:event_btnLimActionPerformed

    private void btnLim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLim1ActionPerformed
        // TODO add your handling code here:
        contRe=1;
        rengs = new ArrayList<>();
        reng="";
        jtaRenglones.setText("");
    }//GEN-LAST:event_btnLim1ActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        // TODO add your handling code here:
        String encabezados[] = new String[enca.size()];
        String renglones[] = new String[rengs.size()];
        
        for(int i=0;i<enca.size();i++){
            encabezados[i] = enca.get(i);
        }
        for(int i=0;i<rengs.size();i++){
            renglones[i]=rengs.get(i);
        }
        
        Object[][] borrador= new Object[renglones.length][encabezados.length];
        
        for(int i=0;i<renglones.length;i++){
            for(int j=0;j<encabezados.length;j++){
                if(j==0){
                    borrador[i][j] = renglones[i];
                }else{
                    borrador[i][j]=null;
                }
            }
        }
        
        Class type[]= new Class[encabezados.length];
        for(int i=0;i<encabezados.length;i++){
            if(i==0){
                type[i]=java.lang.String.class;
            }else{
                type[i]=java.lang.Double.class;
            }
        }
        
        boolean[] canEdit = new boolean[encabezados.length];
        for(int i=0;i<encabezados.length;i++){
            if(i==0){
                canEdit[i]=false;
            }else{
                canEdit[i]=true;
            }
        }
        
        Tabla tabla = new Tabla(borrador,encabezados,type,canEdit);
        
        this.dispose();
    }//GEN-LAST:event_btnTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngreTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngreTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngreTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngreTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngreTab dialog = new IngreTab(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIng;
    private javax.swing.JButton btnIng1;
    private javax.swing.JButton btnLim;
    private javax.swing.JButton btnLim1;
    private javax.swing.JButton btnMasC;
    private javax.swing.JButton btnMasF;
    private javax.swing.JButton btnMenC;
    private javax.swing.JButton btnMenF;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtaLista;
    private javax.swing.JTextArea jtaRenglones;
    private javax.swing.JTextField jtfCol;
    private javax.swing.JTextField jtfFi;
    private javax.swing.JTextField jtfIngEnc;
    private javax.swing.JTextField jtfIngRe;
    // End of variables declaration//GEN-END:variables
}
