/*
 * Hola!
 */
package ventanas;

import java.text.DecimalFormat;
import javax.swing.UIManager;

/**
 *
 * @author Sebastián Méndez <ITCH>
 */
public class Binomial extends javax.swing.JDialog {

    /**
     * Creates new form Binomial
     */
    public Binomial(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        bgIntervalos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpIntervalos = new javax.swing.JPanel();
        jrbIgual = new javax.swing.JRadioButton();
        jrbMenor = new javax.swing.JRadioButton();
        jrbMayor = new javax.swing.JRadioButton();
        jrbMayorIgual = new javax.swing.JRadioButton();
        jrbMenorIgual = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jtfN = new javax.swing.JTextField();
        jtfX = new javax.swing.JTextField();
        jtfP = new javax.swing.JTextField();
        jtfQ = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfRes = new javax.swing.JTextField();

        jButton5.setText("jButton5");

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribucion Binomial");
        setBounds(new java.awt.Rectangle(0, 0, 490, 310));

        jLabel1.setText("n = ");

        jLabel2.setText("x = ");

        jLabel3.setText("p = ");

        jLabel4.setText("q =");

        jpIntervalos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bgIntervalos.add(jrbIgual);
        jrbIgual.setText("X = x");

        bgIntervalos.add(jrbMenor);
        jrbMenor.setText("X < x");

        bgIntervalos.add(jrbMayor);
        jrbMayor.setText("X > x");

        bgIntervalos.add(jrbMayorIgual);
        jrbMayorIgual.setText("X >= X");

        bgIntervalos.add(jrbMenorIgual);
        jrbMenorIgual.setText("X <= x");

        jLabel6.setText("Binomial");

        jLabel7.setText("Binomial acumulada");

        javax.swing.GroupLayout jpIntervalosLayout = new javax.swing.GroupLayout(jpIntervalos);
        jpIntervalos.setLayout(jpIntervalosLayout);
        jpIntervalosLayout.setHorizontalGroup(
            jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntervalosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIntervalosLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIntervalosLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jpIntervalosLayout.createSequentialGroup()
                        .addGroup(jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jrbIgual)
                            .addComponent(jLabel7)
                            .addGroup(jpIntervalosLayout.createSequentialGroup()
                                .addGroup(jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbMenorIgual)
                                    .addComponent(jrbMenor))
                                .addGap(18, 18, 18)
                                .addGroup(jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbMayor)
                                    .addComponent(jrbMayorIgual))))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        jpIntervalosLayout.setVerticalGroup(
            jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntervalosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jrbIgual)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMenor)
                    .addComponent(jrbMayor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpIntervalosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMenorIgual)
                    .addComponent(jrbMayorIgual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtfP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtfPCaretUpdate(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel5.setText("Resultado: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfX))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcular)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfP)
                                .addComponent(jtfQ)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jpIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double fac_n = 1, fac_x = 1, facnx = 1, p_x, p_menos = 0;

        int n = Integer.parseInt(jtfN.getText());
        int x = Integer.parseInt(jtfX.getText());
        double p = Double.parseDouble(jtfP.getText());
        double q = 1 - p;

        if (jrbIgual.isSelected()) {

            //FACTORIALES
            for (int i = 1; i <= n; i++) {//factorial de n
                fac_n = fac_n * i;
            }
            for (int i = 1; i <= x; i++) {//factorial de x
                fac_x = fac_x * i;
            }
            for (int i = 1; i <= (n - x); i++) {//factorial de n-x
                facnx = facnx * i;
            }
            //Fórmula
            p_x = (fac_n / (fac_x * facnx)) * Math.pow(p, x) * Math.pow(q, n - x);
            DecimalFormat formateador = new DecimalFormat("##.##%");//convierte el porcentaje
            jtfRes.setText(formateador.format(p_x));
        } else if (jrbMenor.isSelected()) {
            for (int j = 0; j < x; j++) {
                //FACTORIALES
                for (int i = 1; i <= n; i++) {//factorial de n
                    fac_n = fac_n * i;
                }
                for (int i = 1; i <= j; i++) {//factorial de x
                    fac_x = fac_x * i;
                }
                for (int i = 1; i <= (n - j); i++) {//factorial de n-x
                    facnx = facnx * i;
                }
                //Fórmula
                p_x = (fac_n / (fac_x * facnx)) * Math.pow(p, j) * Math.pow(q, n - j);
                p_menos = p_menos + p_x;
                fac_n = 1;
                fac_x = 1;
                facnx = 1;
                p_x = 0;
            }//for
            DecimalFormat forma = new DecimalFormat("##.##%");//convierte el porcentaje
            jtfRes.setText(forma.format(p_menos));
        } else if (jrbMenorIgual.isSelected()) {
            for (int j = 0; j <= x; j++) {
                //FACTORIALES
                for (int i = 1; i <= n; i++) {//factorial de n
                    fac_n = fac_n * i;
                }
                for (int i = 1; i <= j; i++) {//factorial de x
                    fac_x = fac_x * i;
                }
                for (int i = 1; i <= (n - j); i++) {//factorial de n-x
                    facnx = facnx * i;
                }
                //Fórmula
                p_x = (fac_n / (fac_x * facnx)) * Math.pow(p, j) * Math.pow(q, n - j);
                p_menos = p_menos + p_x;
                fac_n = 1;
                fac_x = 1;
                facnx = 1;
                p_x = 0;
            }//for
            DecimalFormat porciento = new DecimalFormat("##.##%");//convierte el porcentaje
            jtfRes.setText(porciento.format(p_menos));
        } else if (jrbMayor.isSelected()) {
            for (int j = 0; j <= x; j++) {
                //FACTORIALES
                for (int i = 1; i <= n; i++) {//factorial de n
                    fac_n = fac_n * i;
                }
                for (int i = 1; i <= j; i++) {//factorial de x
                    fac_x = fac_x * i;
                }
                for (int i = 1; i <= (n - j); i++) {//factorial de n-x
                    facnx = facnx * i;
                }
                //Fórmula
                p_x = (fac_n / (fac_x * facnx)) * Math.pow(p, j) * Math.pow(q, n - j);
                p_menos = p_menos + p_x;
                fac_n = 1;
                fac_x = 1;
                facnx = 1;
                p_x = 0;
            }//for
            DecimalFormat forma1 = new DecimalFormat("##.##%");//convierte el porcentaje
            jtfRes.setText(forma1.format(p_menos));
        } else if (jrbMayorIgual.isSelected()) {
            for (int j = 0; j < x; j++) {
                //FACTORIALES
                for (int i = 1; i <= n; i++) {//factorial de n
                    fac_n = fac_n * i;
                }
                for (int i = 1; i <= j; i++) {//factorial de x
                    fac_x = fac_x * i;
                }
                for (int i = 1; i <= (n - j); i++) {//factorial de n-x
                    facnx = facnx * i;
                }
                //Fórmula
                p_x = (fac_n / (fac_x * facnx)) * Math.pow(p, j) * Math.pow(q, n - j);
                p_menos = p_menos + p_x;
                fac_n = 1;
                fac_x = 1;
                facnx = 1;
                p_x = 0;
            }//for
            DecimalFormat forma2 = new DecimalFormat("##.##%");//convierte el porcentaje
            jtfRes.setText(forma2.format(p_menos));
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jtfPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtfPCaretUpdate
        // TODO add your handling code here:
        if (!jtfP.getText().isEmpty()) {
            double p = Double.parseDouble(jtfP.getText());
            if (p > 0 && p < 1) {
                jtfQ.setText("" + (1 - p));
            }
        } else {
            jtfQ.setText("");
        }
    }//GEN-LAST:event_jtfPCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Binomial dialog = new Binomial(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgIntervalos;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpIntervalos;
    private javax.swing.JRadioButton jrbIgual;
    private javax.swing.JRadioButton jrbMayor;
    private javax.swing.JRadioButton jrbMayorIgual;
    private javax.swing.JRadioButton jrbMenor;
    private javax.swing.JRadioButton jrbMenorIgual;
    private javax.swing.JTextField jtfN;
    private javax.swing.JTextField jtfP;
    private javax.swing.JTextField jtfQ;
    private javax.swing.JTextField jtfRes;
    private javax.swing.JTextField jtfX;
    // End of variables declaration//GEN-END:variables
}
