/*
 * Hola!
 */
package ventanas;

import javax.swing.UIManager;

/**
 *
 * @author Sebastián Méndez <ITCH>
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBino = new javax.swing.JButton();
        btnHiper = new javax.swing.JButton();
        btnPois = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnChi = new javax.swing.JButton();
        btnTst = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        jlbFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 750, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setText("Distribuciones muestrales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Graf06.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 109, -1, 186));

        btnBino.setBackground(new java.awt.Color(0, 0, 0));
        btnBino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBino.setText("Binomial y binomial acumulada");
        btnBino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        btnHiper.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHiper.setText("Hipergeometrica");
        btnHiper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHiperActionPerformed(evt);
            }
        });
        getContentPane().add(btnHiper, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        btnPois.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPois.setText("Poisson y poisson acumulada");
        btnPois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoisActionPerformed(evt);
            }
        });
        getContentPane().add(btnPois, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        btnNormal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNormal.setText("Normal");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });
        getContentPane().add(btnNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        btnChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChi.setText("Chi cuadrada");
        btnChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiActionPerformed(evt);
            }
        });
        getContentPane().add(btnChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btnTst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTst.setText("T-student");
        btnTst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTstActionPerformed(evt);
            }
        });
        getContentPane().add(btnTst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        btnF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        getContentPane().add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jlbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1500746658230_1.png"))); // NOI18N
        getContentPane().add(jlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 480));

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem2.setText("Acerca del equipo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinoActionPerformed
        // TODO add your handling code here:
        Binomial bin = new Binomial(new javax.swing.JDialog(),true);
        bin.setVisible(true);
    }//GEN-LAST:event_btnBinoActionPerformed

    private void btnTstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTstActionPerformed
        // TODO add your handling code here:
        String direccion = "https://www.easycalculation.com/es/statistics/critical-t-test.php";
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + direccion);
        } catch (Exception err) {
            System.out.println("Error: "+err);
        }
    }//GEN-LAST:event_btnTstActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        // TODO add your handling code here:
        String direccion = "https://www.easycalculation.com/es/statistics/f-test-p-value.php";
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + direccion);
        } catch (Exception err) {
            System.out.println("Error: "+err);
        }
    }//GEN-LAST:event_btnFActionPerformed

    private void btnChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiActionPerformed
        // TODO add your handling code here:
        ChiCuadrada chi = new ChiCuadrada(new javax.swing.JDialog(),true);
        chi.setVisible(true);
    }//GEN-LAST:event_btnChiActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        // TODO add your handling code here:
        Normal no = new Normal(new javax.swing.JDialog(),true);
        no.setVisible(true);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AcerDe ac = new AcerDe(new javax.swing.JDialog(),true);
        ac.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnHiperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiperActionPerformed
        // TODO add your handling code here:
        HiperGeo hg = new HiperGeo(new javax.swing.JDialog(),true);
        hg.setVisible(true);
    }//GEN-LAST:event_btnHiperActionPerformed

    private void btnPoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoisActionPerformed
        // TODO add your handling code here:
        Poisson po = new Poisson(new javax.swing.JDialog(),true);
        po.setVisible(true);
    }//GEN-LAST:event_btnPoisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBino;
    private javax.swing.JButton btnChi;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnHiper;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnPois;
    private javax.swing.JButton btnTst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel jlbFondo;
    // End of variables declaration//GEN-END:variables
}
